import { useState } from 'react'
import { ArrowLeft, Download, FileText, Loader2 } from 'lucide-react'
import type { LiveSession, StoryArtifact, StoryContext } from '../types'
import { downloadStoryPdf } from '../api/client'

interface FinalStoryProps {
  story: StoryContext
  session: LiveSession
  artifact: StoryArtifact
  onStartOver: () => void
}

export function FinalStory({
  story,
  session,
  artifact,
  onStartOver,
}: FinalStoryProps) {
  const [downloading, setDownloading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const draft = artifact.draft

  async function download() {
    setDownloading(true)
    setError(null)
    try {
      await downloadStoryPdf(session, artifact.download_url, draft.title)
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Download failed')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="min-h-full bg-[#fdfbf7]">
      <div className="mx-auto max-w-5xl px-6 py-10 md:py-16">
        <div className="mb-10 flex flex-wrap items-start justify-between gap-5 border-b border-line pb-8">
          <div>
            <p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-ember">
              <FileText size={14} /> Final story
            </p>
            <h1 className="font-display text-4xl text-parchment md:text-5xl">
              {draft.title}
            </h1>
            <p className="mt-2 text-sm text-mist">
              Reviewed and assembled from your live writers’ room.
            </p>
          </div>
          <button
            type="button"
            onClick={() => void download()}
            disabled={downloading || !artifact.download_url}
            className="inline-flex items-center gap-2 rounded-full bg-parchment px-5 py-3 text-sm font-semibold text-ink disabled:opacity-40"
          >
            {downloading ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
            Download PDF
          </button>
        </div>

        {error && <p className="mb-6 rounded-lg bg-rose/10 px-4 py-3 text-sm text-rose">{error}</p>}

        <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_280px]">
          <article className="whitespace-pre-wrap font-display text-xl leading-[1.85] text-parchment">
            {draft.narrative || story.text}
          </article>

          <aside className="space-y-8">
            <ReviewList
              title="What changed"
              items={draft.change_summary}
              empty="No material changes were recorded."
            />
            <ReviewList
              title="Unresolved questions"
              items={draft.unresolved_questions}
              empty="No unresolved questions."
            />
            <div className="border-t border-line pt-5 font-mono text-[10px] leading-relaxed text-mist">
              Artifact {artifact.artifact_id || 'generated by export endpoint'}
            </div>
          </aside>
        </div>

        <div className="mt-14 border-t border-line pt-8">
          <button type="button" onClick={onStartOver} className="inline-flex items-center gap-2 text-sm font-medium text-mist hover:text-parchment">
            <ArrowLeft size={15} /> Start another story
          </button>
        </div>
      </div>
    </div>
  )
}

function ReviewList({
  title,
  items,
  empty,
}: {
  title: string
  items: string[]
  empty: string
}) {
  return (
    <section>
      <h2 className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-ember">{title}</h2>
      {items.length ? (
        <ul className="space-y-3 text-sm leading-relaxed text-parchment-dim">
          {items.map((item, index) => (
            <li key={`${item}-${index}`} className="border-l-2 border-line pl-3">{item}</li>
          ))}
        </ul>
      ) : (
        <p className="text-sm text-mist">{empty}</p>
      )}
    </section>
  )
}
